name: Debug GitHub Contributions Image

on:
  workflow_dispatch:

jobs:
  debug-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get GitHub Contributions Chart
      run: |
        curl "https://github-contributions-svg.vercel.app/?username=NandoLu&theme=tokyonight" > contributions.svg
        cat contributions.svg
