name: Generate GitHub Contributions Image

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub Contributions Image
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: 'NandoLu'
          template: 'classic'
          base: 'header, activity, community, repositories, metadata'
          filename: 'contributions.svg'
          plugin_isocalendar: 'yes'
          plugin_isocalendar_duration: 'full-year'

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add contributions.svg
          git pull --rebase origin main # Adicionei este comando para evitar conflitos
          git commit -m "Update contributions chart" || true
          git push
