name: Generate GitHub Contributions Image

on:
  schedule:
    - cron: '0 0 * * *' # Executa uma vez por dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate contributions.svg
        uses: Meldiron/github-contributions-calendar@master
        with:
          user: 'NandoLu'
          output: 'contributions.svg'
          # Você pode adicionar um tema aqui se quiser, como
          # theme: 'dark'

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add contributions.svg
          git commit -m "chore: Update contributions.svg" || true
          git push
