name: Generate GitHub Contributions Image

on:
  schedule:
    - cron: '0 0 * * *' # Executa uma vez por dia à meia-noite
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate GitHub Contributions Chart
        uses: lowlighter/metrics@latest
        with:
          filename: contributions.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          template: classic
          config_timezone: America/Sao_Paulo
          committer_message: "Update contributions chart"
