name: Generate GitHub Contributions Image

on:
  schedule:
    - cron: '0 0 * * *' # Executa uma vez por dia à meia-noite
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get GitHub Contributions Chart
      run: |
        curl "https://github-profile-summary-cards.vercel.app/api/cards/profile?username=NandoLu&theme=tokyonight" > contributions-chart.svg
    
    - name: Commit and Push
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add contributions-chart.svg
        git commit -m "Update contributions chart" || true
        git push
