name: Generate GitHub Contributions Grid

on:
  schedule:
    - cron: '0 0 * * *' # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate-grid:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contributions image
        uses: Platane/github-contributions-action@v1
        with:
          username: NandoLu
          output: contributions.svg

      - name: Commit and push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add contributions.svg
          git commit -m "Atualiza imagem de contribuições"
          git push
