name: Generate GitHub Contributions Image

on:
  schedule:
    - cron: '0 0 * * *' # Executa uma vez por dia à meia-noite
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Generate GitHub Contributions Image
        uses: Platane/github-contributions-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output_image_path: 'contributions.png'
          username: 'NandoLu'
          # Use o tema que se aproxima mais da imagem que você quer
          theme: 'dark_dimmed'

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add contributions.png
          git pull --rebase origin main
          git commit -m "Update contributions chart" || true
          git push
